// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdoosudawkjxnusrboam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkb29zdWRhd2tqeG51c3Jib2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjIwMDcsImV4cCI6MjA2NzEzODAwN30.6a1xbsWfHV3WRDW1A4h8XhZkSuh8IyJX3yooZPwGQ6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});